INSERT INTO tbl_booktitle (title) VALUES("Machine Learning and Its Applications");
INSERT INTO tbl_booktitle (title) VALUES("AISC/MKM/Calculemus");
INSERT INTO tbl_booktitle (title) VALUES("Symbolic Algebraic Methods and Verification Methods");
INSERT INTO tbl_booktitle (title) VALUES("AIED");
INSERT INTO tbl_booktitle (title) VALUES("Temporal Databases");
INSERT INTO tbl_booktitle (title) VALUES("ACRI");
INSERT INTO tbl_booktitle (title) VALUES("Algebraic Logic and Universal Algebra in Computer Science");
INSERT INTO tbl_booktitle (title) VALUES("Workshop on Abstract State Machines");
INSERT INTO tbl_booktitle (title) VALUES("VMIL");
INSERT INTO tbl_booktitle (title) VALUES("AAAI/IAAI, Vol. 2");
INSERT INTO tbl_booktitle (title) VALUES("AAAI/IAAI, Vol. 1");
INSERT INTO tbl_booktitle (title) VALUES("Pattern Discovery in Biomolecular Data");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Information Science and Technology (I)");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("ACCV (2)");
INSERT INTO tbl_booktitle (title) VALUES("AAAI");
INSERT INTO tbl_booktitle (title) VALUES("ALGOL 68 Implementation");
INSERT INTO tbl_booktitle (title) VALUES("Analysis of Dynamical and Cognitive Systems");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Logic in Artificial Intelligence and Logic Programming, Volume 2");
INSERT INTO tbl_booktitle (title) VALUES("ACSD");
INSERT INTO tbl_booktitle (title) VALUES("ACSC");
INSERT INTO tbl_booktitle (title) VALUES("AOIS@AAMAS");
INSERT INTO tbl_booktitle (title) VALUES("Query Processing for Advanced Database Systems, Dagstuhl");
INSERT INTO tbl_booktitle (title) VALUES("ACCV (1)");
INSERT INTO tbl_booktitle (title) VALUES("Symposium on Designing Interactive Systems");
INSERT INTO tbl_booktitle (title) VALUES("Theory and Applications of Relational Structures as Knowledge Instruments");
INSERT INTO tbl_booktitle (title) VALUES("Query Processing in Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("APVIS");
INSERT INTO tbl_booktitle (title) VALUES("Database Transaction Models for Advanced Applications");
INSERT INTO tbl_booktitle (title) VALUES("AICS");
INSERT INTO tbl_booktitle (title) VALUES("AICT");
INSERT INTO tbl_booktitle (title) VALUES("AIPS Workshop on Planning for Temporal Domains");
INSERT INTO tbl_booktitle (title) VALUES("Lectures on Concurrency and Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("Abstract Software Specifications");
INSERT INTO tbl_booktitle (title) VALUES("Three-Dimensional Image Capture and Applications");
INSERT INTO tbl_booktitle (title) VALUES("ACPC");
INSERT INTO tbl_booktitle (title) VALUES("Hochleistungs-Transaktionssysteme");
INSERT INTO tbl_booktitle (title) VALUES("ANTS");
INSERT INTO tbl_booktitle (title) VALUES("Universal Access in Ambient Intelligence Environments");
INSERT INTO tbl_booktitle (title) VALUES("ANTS Workshop");
INSERT INTO tbl_booktitle (title) VALUES("AFSS");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Petri Nets: The DEMON Project");
INSERT INTO tbl_booktitle (title) VALUES("Future Parallel Computers");
INSERT INTO tbl_booktitle (title) VALUES("Knowledge Discovery in Databases");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Data Base Theory");
INSERT INTO tbl_booktitle (title) VALUES("Flexible Working - New Network Technologies");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Logic in Artificial Intelligence and Logic Programming (2)");
INSERT INTO tbl_booktitle (title) VALUES("Multi-Agent Programming");
INSERT INTO tbl_booktitle (title) VALUES("ASID");
INSERT INTO tbl_booktitle (title) VALUES("Conference on Analysis of Neural Network Applications");
INSERT INTO tbl_booktitle (title) VALUES("APAQS");
INSERT INTO tbl_booktitle (title) VALUES("ArgMAS");
INSERT INTO tbl_booktitle (title) VALUES("ATL");
INSERT INTO tbl_booktitle (title) VALUES("ACL Workshop on Natural Language Processing in the Biomedical Domain");
INSERT INTO tbl_booktitle (title) VALUES("ARCS Workshops");
INSERT INTO tbl_booktitle (title) VALUES("Artificial Evolution");
INSERT INTO tbl_booktitle (title) VALUES("GULP-PRODE");
INSERT INTO tbl_booktitle (title) VALUES("ARES");
INSERT INTO tbl_booktitle (title) VALUES("AMTA");
INSERT INTO tbl_booktitle (title) VALUES("Afrigraph");
INSERT INTO tbl_booktitle (title) VALUES("AOSE");
INSERT INTO tbl_booktitle (title) VALUES("AINTEC");
INSERT INTO tbl_booktitle (title) VALUES("Mobile Communications");
INSERT INTO tbl_booktitle (title) VALUES("Building an Object-Oriented Database System, The Story of O2");
INSERT INTO tbl_booktitle (title) VALUES("L Systems");
INSERT INTO tbl_booktitle (title) VALUES("Term Rewriting");
INSERT INTO tbl_booktitle (title) VALUES("Computational Biology and Genome Informatics");
INSERT INTO tbl_booktitle (title) VALUES(" Document Management");
INSERT INTO tbl_booktitle (title) VALUES("Text Mining");
INSERT INTO tbl_booktitle (title) VALUES("AFPAC");
INSERT INTO tbl_booktitle (title) VALUES("ARCS");
INSERT INTO tbl_booktitle (title) VALUES("Theoretical Aspects of Computer Science");
INSERT INTO tbl_booktitle (title) VALUES("Database System Concepts, 4th Edition.");
INSERT INTO tbl_booktitle (title) VALUES("Uncertainty Management in Information Systems");
INSERT INTO tbl_booktitle (title) VALUES("Computer Science Today");
INSERT INTO tbl_booktitle (title) VALUES("Automation, Control, and Information Technology");
INSERT INTO tbl_booktitle (title) VALUES("Abstract State Machines");
INSERT INTO tbl_booktitle (title) VALUES("Evolutionary Computing, AISB Workshop");
INSERT INTO tbl_booktitle (title) VALUES("APDC");
INSERT INTO tbl_booktitle (title) VALUES("Application and Theory of Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("Software Development and Ada");
INSERT INTO tbl_booktitle (title) VALUES("ACM Annual Conference (2)");
INSERT INTO tbl_booktitle (title) VALUES("Embedded Systems");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Topics in Artificial Intelligence");
INSERT INTO tbl_booktitle (title) VALUES("ACNS");
INSERT INTO tbl_booktitle (title) VALUES("ASYNC");
INSERT INTO tbl_booktitle (title) VALUES("AC");
INSERT INTO tbl_booktitle (title) VALUES("AOIS@CAiSE");
INSERT INTO tbl_booktitle (title) VALUES("Research Foundations in Object-Oriented and Semantic Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("AH");
INSERT INTO tbl_booktitle (title) VALUES("AICCSA");
INSERT INTO tbl_booktitle (title) VALUES("AOSD Industry Track");
INSERT INTO tbl_booktitle (title) VALUES("ALGOSENSORS");
INSERT INTO tbl_booktitle (title) VALUES("RelMiCS");
INSERT INTO tbl_booktitle (title) VALUES("Computer-Aided Database Design: the DATAID approach");
INSERT INTO tbl_booktitle (title) VALUES("Grid Computing");
INSERT INTO tbl_booktitle (title) VALUES("Art-QoS");
INSERT INTO tbl_booktitle (title) VALUES("APBC");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Distributed Systems");
INSERT INTO tbl_booktitle (title) VALUES("Concurrency and Hardware Design");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Transaction Models and Architectures");
INSERT INTO tbl_booktitle (title) VALUES("AES Candidate Conference");
INSERT INTO tbl_booktitle (title) VALUES("European Workshop on Applications and Theory of Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("IEEE ICCI");
INSERT INTO tbl_booktitle (title) VALUES("Computer Architecture");
INSERT INTO tbl_booktitle (title) VALUES("Computational Discrete Mathematics");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Computational Intelligence and Learning");
INSERT INTO tbl_booktitle (title) VALUES("MSPC");
INSERT INTO tbl_booktitle (title) VALUES("Agile Development Conference");
INSERT INTO tbl_booktitle (title) VALUES("CSCL-Kompendium");
INSERT INTO tbl_booktitle (title) VALUES("Logic and Data Bases");
INSERT INTO tbl_booktitle (title) VALUES("Logic Programming: Functions, Relations, and Equations");
INSERT INTO tbl_booktitle (title) VALUES("InVis.au");
INSERT INTO tbl_booktitle (title) VALUES("Active Rules in Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("ISCA PDCS");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS Research Communications");
INSERT INTO tbl_booktitle (title) VALUES("APNOMS");
INSERT INTO tbl_booktitle (title) VALUES("Compontent Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("AISCM");
INSERT INTO tbl_booktitle (title) VALUES("ALIFE");
INSERT INTO tbl_booktitle (title) VALUES("AACC");
INSERT INTO tbl_booktitle (title) VALUES("Information Modeling Methods and Methodologies");
INSERT INTO tbl_booktitle (title) VALUES("Multimedia Databases in Perspective");
INSERT INTO tbl_booktitle (title) VALUES("ANNIIP");
INSERT INTO tbl_booktitle (title) VALUES("Web-Powered Databases");
INSERT INTO tbl_booktitle (title) VALUES("ACM Annual Conference (1)");
INSERT INTO tbl_booktitle (title) VALUES("AP2PC");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS");
INSERT INTO tbl_booktitle (title) VALUES("Active Mining");
INSERT INTO tbl_booktitle (title) VALUES("Australian Database Conference");
INSERT INTO tbl_booktitle (title) VALUES("AIME");
INSERT INTO tbl_booktitle (title) VALUES("ANTS Conference");
INSERT INTO tbl_booktitle (title) VALUES("IEEE Symposium on Computer Arithmetic");
INSERT INTO tbl_booktitle (title) VALUES("ACiD");
INSERT INTO tbl_booktitle (title) VALUES("Assistive Technology and Artificial Intelligence");
INSERT INTO tbl_booktitle (title) VALUES("ACSAC");
INSERT INTO tbl_booktitle (title) VALUES("IEEE SCC");
INSERT INTO tbl_booktitle (title) VALUES("ASIACRYPT");
INSERT INTO tbl_booktitle (title) VALUES("ARVLSI");
INSERT INTO tbl_booktitle (title) VALUES("COLING-ACL");
INSERT INTO tbl_booktitle (title) VALUES("APWeb");
INSERT INTO tbl_booktitle (title) VALUES("Computer Security and Industrial Cryptography");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Modal Logic");
INSERT INTO tbl_booktitle (title) VALUES("Ökonomische, technische und juristische Perspektiven");
INSERT INTO tbl_booktitle (title) VALUES("ADIS");
INSERT INTO tbl_booktitle (title) VALUES("ACII");
INSERT INTO tbl_booktitle (title) VALUES("AICT/ICIW");
INSERT INTO tbl_booktitle (title) VALUES("AMiRE");
INSERT INTO tbl_booktitle (title) VALUES("Applied Informatics");
INSERT INTO tbl_booktitle (title) VALUES("AINA");
INSERT INTO tbl_booktitle (title) VALUES("IEEE SCW");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Information Science and Technology (IV)");
INSERT INTO tbl_booktitle (title) VALUES("Research Directions in Object-Oriented Programming");
INSERT INTO tbl_booktitle (title) VALUES("Interaction between Compilers and Computer Architectures");
INSERT INTO tbl_booktitle (title) VALUES("ALENEX");
INSERT INTO tbl_booktitle (title) VALUES("Music Education: An Artificial Intelligence Approach");
INSERT INTO tbl_booktitle (title) VALUES("Analysis of Biological Data: A Soft Computing Approach");
INSERT INTO tbl_booktitle (title) VALUES("AAIM");
INSERT INTO tbl_booktitle (title) VALUES(" Datenbanken");
INSERT INTO tbl_booktitle (title) VALUES("ACM Annual Conference - The range of computing: mid-80's perspective");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Networked and Embedded Control Systems");
INSERT INTO tbl_booktitle (title) VALUES("ACL (Companion Volume)");
INSERT INTO tbl_booktitle (title) VALUES("AINA Workshops (2)");
INSERT INTO tbl_booktitle (title) VALUES("AIMDM");
INSERT INTO tbl_booktitle (title) VALUES("ANLP");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS-DASFAA Symposium");
INSERT INTO tbl_booktitle (title) VALUES("Asia-Pacific Computer Systems Architecture Conference");
INSERT INTO tbl_booktitle (title) VALUES("Information Modeling in the New Millennium");
INSERT INTO tbl_booktitle (title) VALUES("Applications in Parallel and Distributed Computing");
INSERT INTO tbl_booktitle (title) VALUES("ADMA");
INSERT INTO tbl_booktitle (title) VALUES("APPROX-RANDOM");
INSERT INTO tbl_booktitle (title) VALUES("AINA Workshops (1)");
INSERT INTO tbl_booktitle (title) VALUES("ät von Entscheidungsproblemen");
INSERT INTO tbl_booktitle (title) VALUES("Implementations of Prolog");
INSERT INTO tbl_booktitle (title) VALUES("SPLAT");
INSERT INTO tbl_booktitle (title) VALUES("AFIPS National Computer Conference");
INSERT INTO tbl_booktitle (title) VALUES("AMKM");
INSERT INTO tbl_booktitle (title) VALUES("Expert Planning Systems");
INSERT INTO tbl_booktitle (title) VALUES("The Industrial Information Technology Handbook");
INSERT INTO tbl_booktitle (title) VALUES("Ant Algorithms");
INSERT INTO tbl_booktitle (title) VALUES("Memory System Performance");
INSERT INTO tbl_booktitle (title) VALUES("AOSD");
INSERT INTO tbl_booktitle (title) VALUES("APPROX");
INSERT INTO tbl_booktitle (title) VALUES("The Data Parallel Programming Model");
INSERT INTO tbl_booktitle (title) VALUES("Future Directions in Distributed Computing");
INSERT INTO tbl_booktitle (title) VALUES("Computers and Education in the 21st Century");
INSERT INTO tbl_booktitle (title) VALUES("Deep Blue Versus Kasparov: The Significance for Artificial Intelligence");
INSERT INTO tbl_booktitle (title) VALUES("Universal Access in Health Telematics");
INSERT INTO tbl_booktitle (title) VALUES("Database Integrity");
INSERT INTO tbl_booktitle (title) VALUES("Selected Papers from the First and the Second European Workshop on Application and Theory of Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("AES Conference");
INSERT INTO tbl_booktitle (title) VALUES("IEEE SCC (1)");
INSERT INTO tbl_booktitle (title) VALUES("Performance of Concurrency Control Mechanisms in Centralized Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("Das ist Informatik");
INSERT INTO tbl_booktitle (title) VALUES("Tree Automata and Languages");
INSERT INTO tbl_booktitle (title) VALUES("ACM Southeast Regional Conference (2)");
INSERT INTO tbl_booktitle (title) VALUES("The TSQL2 Temporal Query Language");
INSERT INTO tbl_booktitle (title) VALUES("ACCV");
INSERT INTO tbl_booktitle (title) VALUES("Active Media Technology");
INSERT INTO tbl_booktitle (title) VALUES("Adaptive Multimedia Retrieval");
INSERT INTO tbl_booktitle (title) VALUES("ASIAN");
INSERT INTO tbl_booktitle (title) VALUES("AAAI Workshop on Intelligent Multimedia Interfaces");
INSERT INTO tbl_booktitle (title) VALUES("APPIA-GULP-PRODE");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Fundamentals of Artificial Intelligence");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Net Theory and Applications");
INSERT INTO tbl_booktitle (title) VALUES("3DIM");
INSERT INTO tbl_booktitle (title) VALUES("The Compiler Design Handbook");
INSERT INTO tbl_booktitle (title) VALUES("ICATPN");
INSERT INTO tbl_booktitle (title) VALUES("European Workshop on Applications and Theory in Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("PLOS");
INSERT INTO tbl_booktitle (title) VALUES("Web Engineering: Systematische Entwicklung von Web-Anwendungen");
INSERT INTO tbl_booktitle (title) VALUES("APWeb Workshops");
INSERT INTO tbl_booktitle (title) VALUES("IEEE SCC (2)");
INSERT INTO tbl_booktitle (title) VALUES("Modern Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("AGTIVE");
INSERT INTO tbl_booktitle (title) VALUES("Object-Oriented Concepts, Databases, and Applications");
INSERT INTO tbl_booktitle (title) VALUES("Coordination of Internet Agents: Models, Technologies, and Applications");
INSERT INTO tbl_booktitle (title) VALUES("AADEBUG");
INSERT INTO tbl_booktitle (title) VALUES("ANNs");
INSERT INTO tbl_booktitle (title) VALUES("Multimedia Data Management");
INSERT INTO tbl_booktitle (title) VALUES("Spatial Databases");
INSERT INTO tbl_booktitle (title) VALUES("APWeb/WAIM Workshops");
INSERT INTO tbl_booktitle (title) VALUES("The Benchmark Handbook");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Distributed Systems");
INSERT INTO tbl_booktitle (title) VALUES("AMEC");
INSERT INTO tbl_booktitle (title) VALUES("Automated Deduction in Geometry");
INSERT INTO tbl_booktitle (title) VALUES("Application of Petri Nets to Communication Networks");
INSERT INTO tbl_booktitle (title) VALUES("Compiler Construction");
INSERT INTO tbl_booktitle (title) VALUES("AIPR");
INSERT INTO tbl_booktitle (title) VALUES("Handbook on Ontologies");
INSERT INTO tbl_booktitle (title) VALUES("AIPS");
INSERT INTO tbl_booktitle (title) VALUES("The INGRES Papers");
INSERT INTO tbl_booktitle (title) VALUES("AGDM");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Computer Entertainment Technology");
INSERT INTO tbl_booktitle (title) VALUES("AGILE");
INSERT INTO tbl_booktitle (title) VALUES("ACM Southeast Regional Conference (1)");
INSERT INTO tbl_booktitle (title) VALUES("AMET");
INSERT INTO tbl_booktitle (title) VALUES("APCCM");
INSERT INTO tbl_booktitle (title) VALUES("ASCILITE");
INSERT INTO tbl_booktitle (title) VALUES("APPT");
INSERT INTO tbl_booktitle (title) VALUES("Chance Discovery");
INSERT INTO tbl_booktitle (title) VALUES("ACIVS");
INSERT INTO tbl_booktitle (title) VALUES("ICAPS");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Microcomputer System Design");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Local Area Networks");
INSERT INTO tbl_booktitle (title) VALUES("IEEE Workshop on Multimedia Signal Processing");
INSERT INTO tbl_booktitle (title) VALUES("AMFG");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Theoretical Computer Science, Volume B: Formal Models and Sematics (B)");
INSERT INTO tbl_booktitle (title) VALUES("ADCS");
INSERT INTO tbl_booktitle (title) VALUES("Coordination Technology for Collaborative Applications");
INSERT INTO tbl_booktitle (title) VALUES("ACISP");
INSERT INTO tbl_booktitle (title) VALUES("State of the Art in Applied Cryptography");
INSERT INTO tbl_booktitle (title) VALUES("AIRS");
INSERT INTO tbl_booktitle (title) VALUES("ADB");
INSERT INTO tbl_booktitle (title) VALUES("ACE");
INSERT INTO tbl_booktitle (title) VALUES("ACG");
INSERT INTO tbl_booktitle (title) VALUES("AISA");
INSERT INTO tbl_booktitle (title) VALUES("AISC");
INSERT INTO tbl_booktitle (title) VALUES("AMCS");
INSERT INTO tbl_booktitle (title) VALUES("ACL");
INSERT INTO tbl_booktitle (title) VALUES("AMCP");
INSERT INTO tbl_booktitle (title) VALUES("Multidimensional Databases");
INSERT INTO tbl_booktitle (title) VALUES("Methodology and Tools for Data Base Design");
INSERT INTO tbl_booktitle (title) VALUES("Australasian Database Conference");
INSERT INTO tbl_booktitle (title) VALUES("Trust in Cyber-societies");
INSERT INTO tbl_booktitle (title) VALUES("ICEC");
INSERT INTO tbl_booktitle (title) VALUES("AFIPS Spring Joint Computing Conference");
INSERT INTO tbl_booktitle (title) VALUES("ABZ");
INSERT INTO tbl_booktitle (title) VALUES("ACM Southeast Regional Conference");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Multimedia Information Management");
INSERT INTO tbl_booktitle (title) VALUES("AMDO");
INSERT INTO tbl_booktitle (title) VALUES("Database Design");
INSERT INTO tbl_booktitle (title) VALUES("Mathematical Models for the Semantics of Parallelism");
INSERT INTO tbl_booktitle (title) VALUES("Petri Nets (2)");
INSERT INTO tbl_booktitle (title) VALUES("AIFIPP");
INSERT INTO tbl_booktitle (title) VALUES("AAECC");
INSERT INTO tbl_booktitle (title) VALUES("ACIS-ICIS");
INSERT INTO tbl_booktitle (title) VALUES("Generic Programming");
INSERT INTO tbl_booktitle (title) VALUES("AI*IA");
INSERT INTO tbl_booktitle (title) VALUES("Cooperative Interfaces to Information Systems");
INSERT INTO tbl_booktitle (title) VALUES("PASA");
INSERT INTO tbl_booktitle (title) VALUES("ALPUK");
INSERT INTO tbl_booktitle (title) VALUES("Accurate Scientific Computations");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Automated Reasoning");
INSERT INTO tbl_booktitle (title) VALUES("AOIS");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Information Science and Technology (V)");
INSERT INTO tbl_booktitle (title) VALUES("ALaRT");
INSERT INTO tbl_booktitle (title) VALUES("AUSCRYPT");
INSERT INTO tbl_booktitle (title) VALUES("Software Reliability Modelling and Identification");
INSERT INTO tbl_booktitle (title) VALUES("AgentLink");
INSERT INTO tbl_booktitle (title) VALUES("AMAI");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS (local proceedings)");
INSERT INTO tbl_booktitle (title) VALUES("ASST");
INSERT INTO tbl_booktitle (title) VALUES("Issues in Agent Communication");
INSERT INTO tbl_booktitle (title) VALUES("ASPLOS");
INSERT INTO tbl_booktitle (title) VALUES("Current Trends in Concurrency");
INSERT INTO tbl_booktitle (title) VALUES("AISM");
INSERT INTO tbl_booktitle (title) VALUES("Entwicklungstendenzen bei Datenbanksystemen");
INSERT INTO tbl_booktitle (title) VALUES("ADT");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Object-Oriented Data Modeling");
INSERT INTO tbl_booktitle (title) VALUES("ADS");
INSERT INTO tbl_booktitle (title) VALUES("ARTS");
INSERT INTO tbl_booktitle (title) VALUES("AMAST");
INSERT INTO tbl_booktitle (title) VALUES("ADL");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Information Processing Techniques for LAN and MAN Management");
INSERT INTO tbl_booktitle (title) VALUES("APCHI");
INSERT INTO tbl_booktitle (title) VALUES("Algebraic and Coalgebraic Methods in the Mathematics of Program Construction");
INSERT INTO tbl_booktitle (title) VALUES("ADC");
INSERT INTO tbl_booktitle (title) VALUES("Agents Workshop on Infrastructure for Multi-Agent Systems");
INSERT INTO tbl_booktitle (title) VALUES("Lectures on Data Security");
INSERT INTO tbl_booktitle (title) VALUES("ANNES");
INSERT INTO tbl_booktitle (title) VALUES("Ada Software Tools Interfaces");
INSERT INTO tbl_booktitle (title) VALUES("ESPRIT ARES Workshop");
INSERT INTO tbl_booktitle (title) VALUES("AISMC");
INSERT INTO tbl_booktitle (title) VALUES("Foundations of Deductive Databases and Logic Programming.");
INSERT INTO tbl_booktitle (title) VALUES("Computers and Education. Towards an Interconnected Society");
INSERT INTO tbl_booktitle (title) VALUES("ADVIS");
INSERT INTO tbl_booktitle (title) VALUES("Annual Simulation Symposium");
INSERT INTO tbl_booktitle (title) VALUES("Handbook of Theoretical Computer Science, Volume A: Algorithms and Complexity (A)");
INSERT INTO tbl_booktitle (title) VALUES("Location-Based Services");
INSERT INTO tbl_booktitle (title) VALUES("International ACM Conference on Assistive Technologies");
INSERT INTO tbl_booktitle (title) VALUES("Ada Deutschland Tagung");
INSERT INTO tbl_booktitle (title) VALUES("The Computer Science and Engineering Handbook");
INSERT INTO tbl_booktitle (title) VALUES("Language Hierarchies and Interfaces");
INSERT INTO tbl_booktitle (title) VALUES("Mathematical Methods of Specification and Synthesis of Software Systems");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Software Engineering");
INSERT INTO tbl_booktitle (title) VALUES("CGIV");
INSERT INTO tbl_booktitle (title) VALUES("AsiaSim");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Functional Programming");
INSERT INTO tbl_booktitle (title) VALUES("ASWC");
INSERT INTO tbl_booktitle (title) VALUES("CIT");
INSERT INTO tbl_booktitle (title) VALUES("Visualizing the Semantic Web");
INSERT INTO tbl_booktitle (title) VALUES("Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("On Object-Oriented Database System");
INSERT INTO tbl_booktitle (title) VALUES("Applications and Theory in Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("AII/ALT");
INSERT INTO tbl_booktitle (title) VALUES("AII");
INSERT INTO tbl_booktitle (title) VALUES("Answer Set Programming");
INSERT INTO tbl_booktitle (title) VALUES("ACSW Frontiers");
INSERT INTO tbl_booktitle (title) VALUES("ISCA PDCCS");
INSERT INTO tbl_booktitle (title) VALUES("AIS");
INSERT INTO tbl_booktitle (title) VALUES("Multimedia Database System: Issues and Research Direction");
INSERT INTO tbl_booktitle (title) VALUES("K4CARE");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS (Local Proceedings)");
INSERT INTO tbl_booktitle (title) VALUES("ALENEX/ANALCO");
INSERT INTO tbl_booktitle (title) VALUES("Types in Logic Programming");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS-DASFAA");
INSERT INTO tbl_booktitle (title) VALUES("Artificial Neural Networks");
INSERT INTO tbl_booktitle (title) VALUES("AAAI/IAAI");
INSERT INTO tbl_booktitle (title) VALUES("AIMSA");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Studies in Biometrics");
INSERT INTO tbl_booktitle (title) VALUES("Domain Modeling and the Duration Calculus");
INSERT INTO tbl_booktitle (title) VALUES("APPSEM");
INSERT INTO tbl_booktitle (title) VALUES("ADCOG");
INSERT INTO tbl_booktitle (title) VALUES("Advances in Knowledge Discovery and Data Mining");
INSERT INTO tbl_booktitle (title) VALUES("Workshop on Agent Communication Languages");
INSERT INTO tbl_booktitle (title) VALUES("ASP-DAC");
INSERT INTO tbl_booktitle (title) VALUES("ASAP");
INSERT INTO tbl_booktitle (title) VALUES("GULP");
INSERT INTO tbl_booktitle (title) VALUES("PACT");
INSERT INTO tbl_booktitle (title) VALUES("The Analysis of Concurrent Systems");
INSERT INTO tbl_booktitle (title) VALUES("AINA (1)");
INSERT INTO tbl_booktitle (title) VALUES("Algebraic Methods");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Net Theory and Applications 1975");
INSERT INTO tbl_booktitle (title) VALUES("AICT/SAPIR/ELETE");
INSERT INTO tbl_booktitle (title) VALUES("AINA Workshops");
INSERT INTO tbl_booktitle (title) VALUES("ACP4IS");
INSERT INTO tbl_booktitle (title) VALUES("System Development and Ada");
INSERT INTO tbl_booktitle (title) VALUES("Knowledge Transformation for the Semantic Web");
INSERT INTO tbl_booktitle (title) VALUES("Applications of Invariance in Computer Vision");
INSERT INTO tbl_booktitle (title) VALUES("Memory System Performance and Correctness");
INSERT INTO tbl_booktitle (title) VALUES("The Data Mining and Knowledge Discovery Handbook");
INSERT INTO tbl_booktitle (title) VALUES(" Algorithms");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Database Technologies and Applications");
INSERT INTO tbl_booktitle (title) VALUES("Australian Software Engineering Conference");
INSERT INTO tbl_booktitle (title) VALUES("Canadian Conference on AI");
INSERT INTO tbl_booktitle (title) VALUES("Agent Modeling");
INSERT INTO tbl_booktitle (title) VALUES("Current Trends in Theoretical Computer Science");
INSERT INTO tbl_booktitle (title) VALUES("ACM Conference on Computer Science");
INSERT INTO tbl_booktitle (title) VALUES("ALENEX/ANALC");
INSERT INTO tbl_booktitle (title) VALUES("Algorithmic Languages and Calculi");
INSERT INTO tbl_booktitle (title) VALUES("Anticipatory Behavior in Adaptive Learning Systems");
INSERT INTO tbl_booktitle (title) VALUES("PacificVis");
INSERT INTO tbl_booktitle (title) VALUES("AKA");
INSERT INTO tbl_booktitle (title) VALUES("ARTDB");
INSERT INTO tbl_booktitle (title) VALUES("Artificial Intelligence Today");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Information Science and Technology (II)");
INSERT INTO tbl_booktitle (title) VALUES("GULP-PRODE (1)");
INSERT INTO tbl_booktitle (title) VALUES("AMT");
INSERT INTO tbl_booktitle (title) VALUES("Unified Modeling Language: Systems Analysis, Design and Development Issues");
INSERT INTO tbl_booktitle (title) VALUES("AMS");
INSERT INTO tbl_booktitle (title) VALUES("GPGPU");
INSERT INTO tbl_booktitle (title) VALUES("Artificial Intelligence and Applications");
INSERT INTO tbl_booktitle (title) VALUES("Unifying Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("AIWoRC");
INSERT INTO tbl_booktitle (title) VALUES("Ada-Europe");
INSERT INTO tbl_booktitle (title) VALUES("Agents");
INSERT INTO tbl_booktitle (title) VALUES("ASSETS");
INSERT INTO tbl_booktitle (title) VALUES("ät von Entscheidungsproblemen 1976");
INSERT INTO tbl_booktitle (title) VALUES("ASWEC");
INSERT INTO tbl_booktitle (title) VALUES("Encyclopedia of Information Science and Technology (III)");
INSERT INTO tbl_booktitle (title) VALUES("Active Database Systems: Triggers and Rules For Advanced Database Processing");
INSERT INTO tbl_booktitle (title) VALUES("GULP-PRODE (2)");
INSERT INTO tbl_booktitle (title) VALUES("ADHOC-NOW");
INSERT INTO tbl_booktitle (title) VALUES("ALT");
INSERT INTO tbl_booktitle (title) VALUES("On the Construction of Programs");
INSERT INTO tbl_booktitle (title) VALUES("AIS-ADM");
INSERT INTO tbl_booktitle (title) VALUES("ALP");
INSERT INTO tbl_booktitle (title) VALUES("AINA (2)");
INSERT INTO tbl_booktitle (title) VALUES("Clustering and Information Retrieval");
INSERT INTO tbl_booktitle (title) VALUES("ADBIS (Short Papers)");
INSERT INTO tbl_booktitle (title) VALUES("Web Dynamics");
INSERT INTO tbl_booktitle (title) VALUES("APSEC");
INSERT INTO tbl_booktitle (title) VALUES("Adaptive Agents and Multi-Agents Systems");
INSERT INTO tbl_booktitle (title) VALUES("Artificial Intelligence and Soft Computing");
INSERT INTO tbl_booktitle (title) VALUES("Logic Programming: Formal Methods and Practical Applications");
INSERT INTO tbl_booktitle (title) VALUES("Method and tools for compiler construction");
INSERT INTO tbl_booktitle (title) VALUES("ACAC");
INSERT INTO tbl_booktitle (title) VALUES("Multimedia Database Systems");
INSERT INTO tbl_booktitle (title) VALUES("Prolog and Databases");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Lectures on Machine Learning");
INSERT INTO tbl_booktitle (title) VALUES("APLAS");
INSERT INTO tbl_booktitle (title) VALUES("APL");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Course: Operating Systems");
INSERT INTO tbl_booktitle (title) VALUES("Data Mining in Bioinformatics");
INSERT INTO tbl_booktitle (title) VALUES("Principles of Database Design (I)");
INSERT INTO tbl_booktitle (title) VALUES("AISB Convention");
INSERT INTO tbl_booktitle (title) VALUES("Applications and Theory of Petri Nets");
INSERT INTO tbl_booktitle (title) VALUES("Adaptive Agents and Multi-Agent Systems");
INSERT INTO tbl_booktitle (title) VALUES("Conference on Designing Interactive Systems");
INSERT INTO tbl_booktitle (title) VALUES("ACM Policy");
INSERT INTO tbl_booktitle (title) VALUES("ätze morgen");
INSERT INTO tbl_booktitle (title) VALUES("ALP/HOA");
INSERT INTO tbl_booktitle (title) VALUES("Readings in Music and Artificial Intelligence");
INSERT INTO tbl_booktitle (title) VALUES("IEEE PACT");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Topics in Database Research, Vol. 1");
INSERT INTO tbl_booktitle (title) VALUES("Datenbankhandbuch");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Topics in Database Research, Vol. 2");
INSERT INTO tbl_booktitle (title) VALUES("Advanced Topics in Database Research, Vol. 3");
INSERT INTO tbl_booktitle (title) VALUES("3DPVT");
