INSERT INTO tbl_publisher (publisher_name) VALUES("McGraw-Hill Book Company");
INSERT INTO tbl_publisher (publisher_name) VALUES("Springer, New York");
INSERT INTO tbl_publisher (publisher_name) VALUES("APress");
INSERT INTO tbl_publisher (publisher_name) VALUES("Garland Publishing, New York");
INSERT INTO tbl_publisher (publisher_name) VALUES("Addison Wesley");
INSERT INTO tbl_publisher (publisher_name) VALUES("MITP-Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("GeoInformation International / John Wiley");
INSERT INTO tbl_publisher (publisher_name) VALUES("Shaker Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("IEEE Signal Processing Society");
INSERT INTO tbl_publisher (publisher_name) VALUES("Plemum Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("SPIE");
INSERT INTO tbl_publisher (publisher_name) VALUES("SIAM");
INSERT INTO tbl_publisher (publisher_name) VALUES("The Association for Computer Linguistics");
INSERT INTO tbl_publisher (publisher_name) VALUES("University Siegen, Germany");
INSERT INTO tbl_publisher (publisher_name) VALUES("Signiform");
INSERT INTO tbl_publisher (publisher_name) VALUES("ISCA");
INSERT INTO tbl_publisher (publisher_name) VALUES("Prentice Hall");
INSERT INTO tbl_publisher (publisher_name) VALUES("Taylor Graham");
INSERT INTO tbl_publisher (publisher_name) VALUES("ÜV Rheinland");
INSERT INTO tbl_publisher (publisher_name) VALUES("Slovak University of Technology, Bratislava");
INSERT INTO tbl_publisher (publisher_name) VALUES("CRC Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("CSLI Publications");
INSERT INTO tbl_publisher (publisher_name) VALUES("L Computer und Literaturverlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("Imperial College Press, London");
INSERT INTO tbl_publisher (publisher_name) VALUES("T Books");
INSERT INTO tbl_publisher (publisher_name) VALUES("W. H. Freeman");
INSERT INTO tbl_publisher (publisher_name) VALUES("The MIT Press and McGraw-Hill Book Company");
INSERT INTO tbl_publisher (publisher_name) VALUES("Harwood Academic publishers");
INSERT INTO tbl_publisher (publisher_name) VALUES("O'Reilly");
INSERT INTO tbl_publisher (publisher_name) VALUES("dpunkt");
INSERT INTO tbl_publisher (publisher_name) VALUES("Computer Science Department III, University of Bonn");
INSERT INTO tbl_publisher (publisher_name) VALUES("ür Informatik");
INSERT INTO tbl_publisher (publisher_name) VALUES("Wiley-Teubner");
INSERT INTO tbl_publisher (publisher_name) VALUES("Verlag Shaker, Aachen");
INSERT INTO tbl_publisher (publisher_name) VALUES("AAAI");
INSERT INTO tbl_publisher (publisher_name) VALUES("Elsevier / Morgan Kaufmann");
INSERT INTO tbl_publisher (publisher_name) VALUES("University of Melbourne, Department of Computer Science");
INSERT INTO tbl_publisher (publisher_name) VALUES("College Publications");
INSERT INTO tbl_publisher (publisher_name) VALUES("AAAI Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("IRM Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("John Wiley");
INSERT INTO tbl_publisher (publisher_name) VALUES("IEEE Computer Society");
INSERT INTO tbl_publisher (publisher_name) VALUES("King's College Publications");
INSERT INTO tbl_publisher (publisher_name) VALUES("CSLI Publications, Stanford, CA");
INSERT INTO tbl_publisher (publisher_name) VALUES("AISB");
INSERT INTO tbl_publisher (publisher_name) VALUES("North-Holland");
INSERT INTO tbl_publisher (publisher_name) VALUES("ACM");
INSERT INTO tbl_publisher (publisher_name) VALUES("Pitman / Morgan Kaufmann");
INSERT INTO tbl_publisher (publisher_name) VALUES("äuser");
INSERT INTO tbl_publisher (publisher_name) VALUES("McGraw-Hill");
INSERT INTO tbl_publisher (publisher_name) VALUES("Idea Group");
INSERT INTO tbl_publisher (publisher_name) VALUES("AFIPS Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("IEEE Computer Society/");
INSERT INTO tbl_publisher (publisher_name) VALUES("mitp-Verlag, Redline GmbH");
INSERT INTO tbl_publisher (publisher_name) VALUES("CSREA Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Thomson Book Company, Washington D.C.");
INSERT INTO tbl_publisher (publisher_name) VALUES("Morgan Kaufmann");
INSERT INTO tbl_publisher (publisher_name) VALUES("Moscow Egineering Physical Institute (Technical University)");
INSERT INTO tbl_publisher (publisher_name) VALUES("Teubner");
INSERT INTO tbl_publisher (publisher_name) VALUES("Benjamin/Cummings");
INSERT INTO tbl_publisher (publisher_name) VALUES("Suomalainen Tiedeakatemia, Helsinki");
INSERT INTO tbl_publisher (publisher_name) VALUES("Microsoft Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Aka Akademische Verlagsgesellschaft Aka GmbH, Berlin");
INSERT INTO tbl_publisher (publisher_name) VALUES("Yourdon Press / Prentice-Hall");
INSERT INTO tbl_publisher (publisher_name) VALUES(" Sons");
INSERT INTO tbl_publisher (publisher_name) VALUES("Hans Huber Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("INSTICC Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Addison-Wesley");
INSERT INTO tbl_publisher (publisher_name) VALUES("ó, Budapest, Hungary");
INSERT INTO tbl_publisher (publisher_name) VALUES(" Row");
INSERT INTO tbl_publisher (publisher_name) VALUES("Cambridge University Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("IEE Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("IASTED/ACTA Press");
INSERT INTO tbl_publisher (publisher_name) VALUES(" Hall");
INSERT INTO tbl_publisher (publisher_name) VALUES("Fischer Taschenbuch Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("IEEE");
INSERT INTO tbl_publisher (publisher_name) VALUES("Vieweg");
INSERT INTO tbl_publisher (publisher_name) VALUES("Institute of Informatics, Faculty of Electrical Engineering and Computer Science, Smetanova 17, IS-2000 Maribor, Slovenia");
INSERT INTO tbl_publisher (publisher_name) VALUES("Springer");
INSERT INTO tbl_publisher (publisher_name) VALUES("City University of Hong Kong");
INSERT INTO tbl_publisher (publisher_name) VALUES("Elsevier");
INSERT INTO tbl_publisher (publisher_name) VALUES("Oldenbourg");
INSERT INTO tbl_publisher (publisher_name) VALUES("Academic Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("ACM Press / Addison-Wesley");
INSERT INTO tbl_publisher (publisher_name) VALUES("Collins");
INSERT INTO tbl_publisher (publisher_name) VALUES("Wadsworth");
INSERT INTO tbl_publisher (publisher_name) VALUES(" Claypool Publishers");
INSERT INTO tbl_publisher (publisher_name) VALUES("MIT Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Van Nostrand Reinhold");
INSERT INTO tbl_publisher (publisher_name) VALUES("ätsverlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("Elsevier and MIT Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Infix Verlag, St. Augustin, Germany");
INSERT INTO tbl_publisher (publisher_name) VALUES("Tampere University of Technology. Pori. Publication");
INSERT INTO tbl_publisher (publisher_name) VALUES("ACM Press and Addison-Wesley");
INSERT INTO tbl_publisher (publisher_name) VALUES("Computer Science Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("WCB/McGraw-Hill");
INSERT INTO tbl_publisher (publisher_name) VALUES("AAAI/MIT Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Physica-Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("W. W. Norton, New York");
INSERT INTO tbl_publisher (publisher_name) VALUES("Copernicus Books, an imprint of Springer-Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("World Scientific");
INSERT INTO tbl_publisher (publisher_name) VALUES("Ellis Horwood");
INSERT INTO tbl_publisher (publisher_name) VALUES("VDE Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("John Benjamins");
INSERT INTO tbl_publisher (publisher_name) VALUES("Australian Computer Society");
INSERT INTO tbl_publisher (publisher_name) VALUES("Prentice-Hall");
INSERT INTO tbl_publisher (publisher_name) VALUES(" Francis");
INSERT INTO tbl_publisher (publisher_name) VALUES("International Thompson Publishing");
INSERT INTO tbl_publisher (publisher_name) VALUES("Oxford University Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("AAAI Press / The MIT Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Nevsky Dialect");
INSERT INTO tbl_publisher (publisher_name) VALUES("QED Publishing Group/John Wiley");
INSERT INTO tbl_publisher (publisher_name) VALUES("Edward Arnold and Halsted Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("Imperial College Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("UNITEC Institute of Technology, Auckland, New Zealand");
INSERT INTO tbl_publisher (publisher_name) VALUES("Butterworth");
INSERT INTO tbl_publisher (publisher_name) VALUES("GI");
INSERT INTO tbl_publisher (publisher_name) VALUES("Eyrolles");
INSERT INTO tbl_publisher (publisher_name) VALUES("HarperCollins");
INSERT INTO tbl_publisher (publisher_name) VALUES("ACM Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("School of Computer and Information Science, Edith Cowan University, Western Australia");
INSERT INTO tbl_publisher (publisher_name) VALUES("Bibliographisches Institut");
INSERT INTO tbl_publisher (publisher_name) VALUES("IOS Press");
INSERT INTO tbl_publisher (publisher_name) VALUES("King's College, London");
INSERT INTO tbl_publisher (publisher_name) VALUES("Carl Hanser Verlag");
INSERT INTO tbl_publisher (publisher_name) VALUES("Kluwer");
INSERT INTO tbl_publisher (publisher_name) VALUES("CEUR-WS.org");
INSERT INTO tbl_publisher (publisher_name) VALUES(" ACM Press");
